---
title: "Посты"
---

# STANDOFF 11: ОТКРЫТЫЙ КИБЕРТУРНИР ДЛЯ ЭТИЧНЫХ ХАКЕРОВ В ЗАМКЕ НА НАБЕРЕЖНОЙ

Киберпреступники не дают покоя никому — ни бизнесу, ни простым гражданам, поэтому очередная битва Standoff, как и фестиваль PHDays, впервые откроет двери широкой публике в рамках настоящего городского киберфестиваля. Тридцать команд атакующих и защитников в этом году соберутся в Парке Горького, где для них возведут целый замок. А на обновленном полигоне появятся дополнительные объекты и новая отрасль экономики — все смогут увидеть, какие последствия произойдут на атомной электростанции в случае атаки хакеров. Участники битвы будут соревноваться в своем мастерстве четыре дня — с 17 по 20 мая.

Цитадель Standoff из камня и песка расположится на Пушкинской набережной в Парке Горького. За счет двух башен высотой 5 и 10 метров твердыня этичных хакеров будет возвышаться над всей территорией форума, а ночью благодаря анимированной подсветке приобретет более технологичный вид. Именно в этой точке открытая для всех желающих зона фестиваля (кибергород) пересечется с технической частью мероприятия — кибердеревней, где состоятся выступления и дискуссии экспертов по ИБ. За перипетиями битвы смогут понаблюдать все посетители парка, успешно прошедшие квест в кибергороде.

За звание сильнейшей на 11-й кибербитве сразятся сразу 20 команд атакующих¹. Топ-5 по итогам Standoff в мае — Codeby, True0xA3, Invuls, DeteAct и EvilBunnyWrote — попадут на противостояние вне конкурса. Остальные команды будут отобраны жюри.

В этом году Standoff пройдет на обновленной платформе. Мы разрабатывали ее последние полгода и верим, что в будущем она позволит нам делать такие битвы еще чаще и масштабнее! Хочу пожелать удачи всем участникам, которых будет больше 200 человек со всего мира.
ЯРОСЛАВ БАБИН,
CPO Standoff 365
НОВОЕ НА КИБЕРПОЛИГОНЕ
Инфраструктура виртуального Государства F² с осенней битвы существенно обновится и расширится: к электроэнергетике, нефтяному сектору и черной металлургии добавится еще атомная промышленность — с АЭС и заводом по обогащению урана. На макете появятся и другие объекты: например, солнечная электростанция и центр диспетчерского управления в энергетике. Развитие инфраструктуры призвано повысить уровень благосостояния граждан Государства F и сделать их жизнь комфортнее. Освоение мирного атома, например, защитит их от энергетических кризисов. Однако каждый дополнительный элемент в этой умной стране несет в себе и новые риски.

Соорганизатором PHDays и Standoff уже третий год выступает ИТ-компания Innostage, разработчик и интегратор сервисов и решений в области цифровой безопасности. Эксперты Innostage обеспечат на кибербитве полную настройку и поддержку средств защиты информации: это позволит синим командам (командам защиты) максимально подробно отслеживать действия хакеров и распутывать инциденты.

На Standoff 11 нападающие попытаются реализовать более 135 недопустимых событий³. Одна только атомная промышленность включает десять новых инцидентов: например, хакеры могут попробовать остановить реактор АЭС, получив доступ к его системе защиты или отключив электроподстанцию. В других отраслях атакующие могут среди прочего вывести из строя коммутаторы технологических сетей нефтеперекачивающей или газораспределительной станции, а также отключить потребителей от солнечной электростанции.

Амбиции хакеров не ограничатся четырьмя отраслями: в Государстве F также есть объекты транспорта, ЖКХ и банковской сферы. Больше всего новых недопустимых событий на Standoff 11 приходится именно на финансы и банки. С помощью платежного хаба партнеров кибербитвы, компании eKassir, в виртуальной стране организован централизованный прием платежей и переводов через любые каналы обслуживания, в том числе мобильный банк, банкоматы и кассы в отделениях.

Большое количество атак на банковский сектор и требования законодательства обязывают нас максимально серьезно относиться к вопросам информационной безопасности. Как разработчик ПО для финансовых организаций eKassir постоянно повышает защищенность своих продуктов: разработка ведется по стандартам SDLC, пройдена сертификация по EMVCo, PA-DSS и ОУД4, в процессе — сертификация по PCI SSF. Мы решили принять участие в Standoff, так как считаем, что проверка на киберполигоне более показательна, чем обычное тестирование на уязвимости: нет ограничений на то, что можно и нельзя взламывать, а атакующие действуют так же, как и реальные хакеры. Это хорошая возможность подтвердить надежность наших продуктов и их устойчивость к кибератакам на практике.
АЛЕКСЕЙ ЗОТОВ,
генеральный директор eKassir
Роль глобального центра реагирования на киберугрозы (SOC, security operation center) в майском противостоянии отведена центру противодействия киберугрозам Innostage CyberART. Опираясь на свои знания и опыт, специалисты проверят каждый отчет о выявленных инцидентах, реализованных и расследованных недопустимых событиях, а также будут сопровождать участников на протяжении всей битвы. Для этого эксперты CyberART формируют судейский блок, команда которого, как и защитники, будет отслеживать шаги атакующих и контролировать каждый элемент инфраструктуры.

Победители Standoff 11 помимо денежного приза и сувениров получат специальный трофей — уникальный кубок. В основе его дизайн-концепции лежит идея противостояния мышления: красная сторона олицетворяет бунтарство и андеграунд, а синяя — сдержанность и знание. Все как в жизни: для построения безопасного будущего этичным хакерам необходимо гармоничное взаимодействие этих качеств.

До встречи на Standoff 11 в Парке Горького!

# Оригинал статья

<https://phdays.com/press-center/news/standoff-11-otkrytyj-kiberturnir-dlya-etichnyh-hakerov-v-zamke-na-naberezhnoj/>
